version: '3.7'
services:
    proxy:
        image: jwilder/nginx-proxy
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        environment:
            - VIRTUAL_HOST=thalia.localhost
    ui:
        build:
            context: .
            dockerfile: ./docker/ui/Dockerfile
        volumes:
            - ./ui:/var/www/html
        tty: true
    relay:
        build:
            context: .
            dockerfile: ./docker/relay/Dockerfile
        volumes:
            - ./relay:/var/www/html
        tty: true
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
            target: 'develop-stage'
        volumes:
            - ./app:/app
            - cargo-cache:/usr/local/cargo/registry
            - target-cache:/app/target
        tty: true
volumes:
    cargo-cache:
    target-cache:
