[package]
name = "app"
version = "0.1.0"
authors = ["Kengo Higashi <shigure@higashi1999.onmicrosoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
